alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias vimy='vim ~/.bash_aliases'
alias vibash='vim ~/.bashrc'
alias sc='source ~/.bashrc'
alias dl='cd ~/Downloads'

alias ..='cd ..'
alias c='clear'
alias proj='cd ~/projects'
alias pydata='source activate pydata'
alias pyexit='source deactivate'
alias nb='jupyter notebook'
alias cpu='top'
alias gpu='watch nvidia-smi'
